import boto3
fraudDetector = boto3.client('frauddetector')

def create_variables():
    fraudDetector.create_variable(name = 'card_bin',variableType = 'CARD_BIN',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'customer_name',variableType = 'BILLING_NAME',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'billing_street',variableType = 'BILLING_ADDRESS_L1',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'billing_city',variableType = 'BILLING_CITY',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'billing_state',variableType = 'BILLING_STATE',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'billing_zip',variableType = 'BILLING_ZIP',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'billing_latitude',variableType = 'CATEGORICAL',dataSource = 'EVENT',dataType = 'FLOAT',defaultValue = 'null')
    fraudDetector.create_variable(name = 'billing_longitude',variableType = 'CATEGORICAL',dataSource = 'EVENT',dataType = 'FLOAT',defaultValue = 'null')
    fraudDetector.create_variable(name = 'customer_job',variableType = 'CATEGORICAL',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'ip_address',variableType = 'IP_ADDRESS',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'customer_email',variableType = 'EMAIL_ADDRESS',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'phone',variableType = 'PHONE_NUMBER',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'user_agent',variableType = 'USERAGENT',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'product_category',variableType = 'PRODUCT_CATEGORY',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'order_price',variableType = 'PRICE',dataSource = 'EVENT',dataType = 'FLOAT',defaultValue = '0.0')
    fraudDetector.create_variable(name = 'payment_currency',variableType = 'CURRENCY_CODE',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')
    fraudDetector.create_variable(name = 'merchant',variableType = 'CATEGORICAL',dataSource = 'EVENT',dataType = 'STRING',defaultValue = 'null')

def delete_variables():
    fraudDetector.delete_variable(name = 'card_bin')
    fraudDetector.delete_variable(name = 'customer_name')
    fraudDetector.delete_variable(name = 'billing_street')
    fraudDetector.delete_variable(name = 'billing_city')
    fraudDetector.delete_variable(name = 'billing_state')
    fraudDetector.delete_variable(name = 'billing_zip')
    fraudDetector.delete_variable(name = 'billing_latitude')
    fraudDetector.delete_variable(name = 'billing_longitude')
    fraudDetector.delete_variable(name = 'customer_job')
    fraudDetector.delete_variable(name = 'ip_address')
    fraudDetector.delete_variable(name = 'customer_email')
    fraudDetector.delete_variable(name = 'phone')
    fraudDetector.delete_variable(name = 'user_agent')
    fraudDetector.delete_variable(name = 'product_category')
    fraudDetector.delete_variable(name = 'order_price')
    fraudDetector.delete_variable(name = 'payment_currency')
    fraudDetector.delete_variable(name = 'merchant')
